# Generated by Django 5.0.1 on 2024-03-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_teacherextra_info'),
        ('edu', '0003_attendance_studentextra_info_cl'),
    ]

    operations = [
    ]
