# Generated by Django 5.0.2 on 2024-04-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10, null=True)),
                ('cl', models.CharField(max_length=12)),
                ('grade_sheet', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=2)),
            ],
        ),
    ]
