# Generated by Django 5.0.2 on 2024-04-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_consultationhour'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationhour',
            name='given_by',
            field=models.CharField(default='education', max_length=20, null=True),
        ),
    ]
