# Generated by Django 5.0.2 on 2024-04-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_consultationhour_given_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationhour',
            name='teacher',
        ),
    ]
