# Generated by Django 5.0.2 on 2024-04-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_grades'),
        ('edu', '0010_message_attachment'),
    ]

    operations = [
    ]
